//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicsInventory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicsInventory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |---STRAIGHT TALK---|
        ///---Phone Inventory---
        ///iPhone 11
        ///Apple
        ///199
        ///835107782971506
        ///===========================
        ///***************************
        ///
        ///|---VERIZON---|
        ///---Phone Inventory---
        ///
        ///***************************
        ///
        ///|---TOTAL BY VERIZON---|
        ///---Phone Inventory---
        ///
        ///***************************
        ///
        ///|---AT&amp;T---|
        ///---Phone Inventory---
        ///
        ///***************************
        ///
        ///|---TRACFONE---|
        ///---Phone Inventory---
        ///
        ///***************************
        ///
        ///|---UNLOCKED---|
        ///---Phone Inventory---
        ///
        ///
        ///.
        /// </summary>
        internal static string Network_Inventories {
            get {
                return ResourceManager.GetString("Network_Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Apple-----
        ///iPhone 11
        ///217093817731
        ///iPhone 12
        ///217093816951
        ///iPhone 13
        ///217093816931
        ///iPhone 14
        ///217093815591
        ///iPhone 15
        ///217093818881
        ///-----Motorola-----
        ///Moto G 5G
        ///342190002960
        ///Moto G Play
        ///342190015550
        ///Moto G Power
        ///342190009880
        ///Moto G Pure
        ///342190010002
        ///Moto G Stylus
        ///342190004510
        ///-----Google-----
        ///Pixel 4
        ///547102938214
        ///Pixel 5
        ///547102932994
        ///Pixel 6a
        ///547102935124
        ///Pixel 7
        ///547102940114
        ///Pixel 8
        ///547102939524
        ///-----Samsung-----
        ///Galaxy A53
        ///392111087550
        ///Galaxy A54
        ///392111089420
        ///Galaxy A2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UPC_Organizer {
            get {
                return ResourceManager.GetString("UPC_Organizer", resourceCulture);
            }
        }
    }
}
